-- Allergy Snatcher Food Import Script
-- Generated by dataimport.py

-- Create a placeholder 'System' user for data attribution
-- and set a variable for its ID.
INSERT IGNORE INTO users (username, email, role, first_name) VALUES ('System', 'system@local.host', 'admin', 'System');
SET @system_user_id = (SELECT id FROM users WHERE username = 'System');

-- Processing food: H-E-B Strawberry Preserves
INSERT IGNORE INTO categories (category) VALUES ('pantry');
SET @category_id = (SELECT id FROM categories WHERE category = 'pantry');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Strawberry Preserves',
    'H-E-B',
    'public',
    50.0,
    0.0,
    12.0,
    0.0,
    13.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Strawberries');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'High Fructose Corn Syrup');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Corn Syrup');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Fruit Pectin');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Citric Acid');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Butter Tortillas
INSERT IGNORE INTO categories (category) VALUES ('bread');
SET @category_id = (SELECT id FROM categories WHERE category = 'bread');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('tex-mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'tex-mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Butter Tortillas',
    'H-E-B',
    'public',
    110.0,
    1.0,
    1.0,
    4.0,
    25.0,
    5.0,
    400.0,
    0.0,
    4.5,
    1.5,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Enriched Bleached Wheat Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Shortening (Soybean Oil, Hydrogenated Soybean Oil)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Butter');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Baking Soda');


-- Processing food: H-E-B Wild Caught Cod Fillets
INSERT IGNORE INTO categories (category) VALUES ('fish');
SET @category_id = (SELECT id FROM categories WHERE category = 'fish');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Wild Caught Cod Fillets',
    'H-E-B',
    'public',
    80.0,
    0.0,
    0.0,
    26.0,
    0.0,
    60.0,
    80.0,
    0.0,
    1.0,
    0.0,
    4.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cod');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Fully Cooked Bacon
INSERT IGNORE INTO categories (category) VALUES ('meat');
SET @category_id = (SELECT id FROM categories WHERE category = 'meat');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Fully Cooked Bacon',
    'H-E-B',
    'public',
    60.0,
    0.0,
    0.0,
    5.0,
    0.0,
    15.0,
    230.0,
    0.0,
    6.0,
    2.0,
    2.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Pork');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sodium Phosphate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sodium Erythorbate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sodium Nitrite');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Pork');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Pork');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Mission Zero Net Carbs Original Flour Tortillas, Street Taco Size
INSERT IGNORE INTO categories (category) VALUES ('ingredient');
SET @category_id = (SELECT id FROM categories WHERE category = 'ingredient');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Mexican');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Mexican');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Mission Zero Net Carbs Original Flour Tortillas, Street Taco Size',
    'Mission',
    'public',
    25.0,
    0.0,
    0.0,
    2.0,
    7.0,
    0.0,
    0.125,
    0.0,
    1.5,
    0.5,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Modified Wheat Starch');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vital Wheat Gluten');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Wheat Gluten Isolate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vegetable Shortening');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Calcium Propionate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sodium Acid Pyrophosphate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Baking Soda');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Distilled Monoglycerides');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sorbic Acid');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Fumaric Acid');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cellulose Gum');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sunflower Oil');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Natural Flavors');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Steviol Glycosides.');


-- Processing food: H-E-B Texas-Shaped Tortilla Chips
INSERT IGNORE INTO categories (category) VALUES ('snacks');
SET @category_id = (SELECT id FROM categories WHERE category = 'snacks');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('tex-mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'tex-mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Texas-Shaped Tortilla Chips',
    'H-E-B',
    'public',
    150.0,
    2.0,
    0.0,
    2.0,
    19.0,
    0.0,
    115.0,
    0.0,
    7.0,
    1.0,
    1.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Corn');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vegetable Oil (Corn, Canola, and/or Sunflower Oil)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Ground Cinnamon
INSERT IGNORE INTO categories (category) VALUES ('ingredient');
SET @category_id = (SELECT id FROM categories WHERE category = 'ingredient');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Ground Cinnamon',
    'H-E-B',
    'public',
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.25,
    'tsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cinnamon');


-- Processing food: H-E-B Uncured Beef Hot Dogs
INSERT IGNORE INTO categories (category) VALUES ('meat');
SET @category_id = (SELECT id FROM categories WHERE category = 'meat');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Uncured Beef Hot Dogs',
    'H-E-B',
    'public',
    130.0,
    0.0,
    1.0,
    6.0,
    1.0,
    30.0,
    480.0,
    0.5,
    13.0,
    5.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Beef');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Spices');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Paprika');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Garlic Powder');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Celery Powder');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Hill Country Fare Shredded Mild Cheddar Cheese
INSERT IGNORE INTO categories (category) VALUES ('dairy');
SET @category_id = (SELECT id FROM categories WHERE category = 'dairy');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Hill Country Fare Shredded Mild Cheddar Cheese',
    'Hill Country Fare',
    'public',
    110.0,
    0.0,
    0.0,
    7.0,
    1.0,
    30.0,
    180.0,
    0.0,
    9.0,
    6.0,
    0.25,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Pasteurized Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cheese Culture');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Enzymes');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Annatto (for color)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Potato Starch and Powdered Cellulose (to prevent caking)');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Lactose');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Lactose');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Cafe Olé by H-E-B Taste of San Antonio Medium Roast Coffee
INSERT IGNORE INTO categories (category) VALUES ('beverages');
SET @category_id = (SELECT id FROM categories WHERE category = 'beverages');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Cafe Olé by H-E-B Taste of San Antonio Medium Roast Coffee',
    'Cafe Olé by H-E-B',
    'public',
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Arabica Coffee Beans');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Natural and Artificial Flavors');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Natural Creamy Peanut Butter
INSERT IGNORE INTO categories (category) VALUES ('pantry');
SET @category_id = (SELECT id FROM categories WHERE category = 'pantry');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Natural Creamy Peanut Butter',
    'H-E-B',
    'public',
    190.0,
    3.0,
    2.0,
    7.0,
    7.0,
    0.0,
    125.0,
    0.0,
    16.0,
    3.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Peanuts');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Bakery White Bread
INSERT IGNORE INTO categories (category) VALUES ('bread');
SET @category_id = (SELECT id FROM categories WHERE category = 'bread');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Bakery White Bread',
    'H-E-B Bakery',
    'public',
    80.0,
    0.0,
    2.0,
    3.0,
    15.0,
    0.0,
    200.0,
    0.0,
    1.5,
    0.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Enriched Wheat Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Soybean Oil');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Yeast');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Mootopia Milk
INSERT IGNORE INTO categories (category) VALUES ('dairy');
SET @category_id = (SELECT id FROM categories WHERE category = 'dairy');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Mootopia Milk',
    'H-E-B',
    'public',
    150.0,
    0.0,
    12.0,
    8.0,
    12.0,
    35.0,
    125.0,
    0.0,
    8.0,
    5.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vitamin D3');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Lactose');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Lactose');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Texas Chili Seasoning Mix
INSERT IGNORE INTO categories (category) VALUES ('Spice mixes');
SET @category_id = (SELECT id FROM categories WHERE category = 'Spice mixes');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Tex-Mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Tex-Mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Texas Chili Seasoning Mix',
    'H-E-B',
    'public',
    30.0,
    2.0,
    0.0,
    1.0,
    5.0,
    0.0,
    410.0,
    0.0,
    1.0,
    0.0,
    1.33,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'CHILI PEPPER AND OTHER SPICES');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'ENRICHED FLOUR (WHEAT FLOUR, NIACIN, IRON, THIAMIN MONONITRATE, RIBOFLAVIN, FOLIC ACID)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'SALT');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'ONION');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'GARLIC');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Original BBQ Sauce
INSERT IGNORE INTO categories (category) VALUES ('condiments');
SET @category_id = (SELECT id FROM categories WHERE category = 'condiments');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Original BBQ Sauce',
    'H-E-B',
    'public',
    50.0,
    0.0,
    15.0,
    0.0,
    17.0,
    0.0,
    290.0,
    0.0,
    0.0,
    0.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tomato Puree');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'High Fructose Corn Syrup');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vinegar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Molasses');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Spices');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Onion Powder');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Garlic Powder');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Natural Smoke Flavor');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Texas Roots Red Onions
INSERT IGNORE INTO categories (category) VALUES ('produce');
SET @category_id = (SELECT id FROM categories WHERE category = 'produce');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Texas Roots Red Onions',
    'H-E-B Texas Roots',
    'public',
    60.0,
    2.0,
    9.0,
    2.0,
    14.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Red Onion');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Creamy Creations 1905 Vanilla Ice Cream
INSERT IGNORE INTO categories (category) VALUES ('frozen dessert');
SET @category_id = (SELECT id FROM categories WHERE category = 'frozen dessert');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Creamy Creations 1905 Vanilla Ice Cream',
    'H-E-B',
    'public',
    230.0,
    0.0,
    18.0,
    3.0,
    19.0,
    50.0,
    55.0,
    0.0,
    10.0,
    6.0,
    0.67,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cream');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Skim Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Corn Syrup');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Egg Yolks');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Natural Vanilla Flavor');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Guar Gum');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tara Gum');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Carrageenan');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Eggs');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Eggs');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Lactose');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Lactose');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Meal Simple by H-E-B Salmon with Asparagus
INSERT IGNORE INTO categories (category) VALUES ('prepared meal');
SET @category_id = (SELECT id FROM categories WHERE category = 'prepared meal');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Meal Simple by H-E-B Salmon with Asparagus',
    'Meal Simple by H-E-B',
    'public',
    400.0,
    3.0,
    2.0,
    35.0,
    5.0,
    85.0,
    300.0,
    0.0,
    20.0,
    4.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salmon');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Asparagus');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Olive Oil');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Black Pepper');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lemon');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Jalapeño Pimento Cheese Dip
INSERT IGNORE INTO categories (category) VALUES ('dips');
SET @category_id = (SELECT id FROM categories WHERE category = 'dips');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Jalapeño Pimento Cheese Dip',
    'H-E-B',
    'public',
    130.0,
    0.0,
    1.0,
    4.0,
    2.0,
    25.0,
    250.0,
    0.0,
    12.0,
    5.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cheddar Cheese');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Mayonnaise');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Pimentos');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Jalapeños');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cream Cheese');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Spices');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Lactose');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Lactose');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Eggs');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Eggs');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Select Ingredients Classic Potato Chips
INSERT IGNORE INTO categories (category) VALUES ('snacks');
SET @category_id = (SELECT id FROM categories WHERE category = 'snacks');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Select Ingredients Classic Potato Chips',
    'H-E-B',
    'public',
    160.0,
    1.0,
    0.0,
    2.0,
    15.0,
    0.0,
    170.0,
    0.0,
    10.0,
    1.5,
    1.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Potatoes');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vegetable Oil (Sunflower, Corn, and/or Canola Oil)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Seasoned Beef Skirt Steak Fajitas
INSERT IGNORE INTO categories (category) VALUES ('meat');
SET @category_id = (SELECT id FROM categories WHERE category = 'meat');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('tex-mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'tex-mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Seasoned Beef Skirt Steak Fajitas',
    'H-E-B',
    'public',
    210.0,
    0.0,
    1.0,
    22.0,
    2.0,
    70.0,
    680.0,
    0.0,
    14.0,
    6.0,
    4.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Beef Skirt Steak');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Seasoning (Spices, Salt, Garlic Powder, Onion Powder)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lime Juice');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Red meat');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Red meat');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Sushiya California Roll
INSERT IGNORE INTO categories (category) VALUES ('prepared meal');
SET @category_id = (SELECT id FROM categories WHERE category = 'prepared meal');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('japanese');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'japanese');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Sushiya California Roll',
    'H-E-B Sushiya',
    'public',
    190.0,
    2.0,
    6.0,
    6.0,
    40.0,
    4.0,
    744.0,
    0.0,
    4.0,
    0.5,
    8.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Rice');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Avocado');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cucumber');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Imitation Crab');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Seaweed');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sesame Seeds');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Shellfish');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Shellfish');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Organics Whole Kernel Corn
INSERT IGNORE INTO categories (category) VALUES ('canned goods');
SET @category_id = (SELECT id FROM categories WHERE category = 'canned goods');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Organics Whole Kernel Corn',
    'H-E-B Organics',
    'public',
    70.0,
    2.0,
    6.0,
    3.0,
    20.0,
    0.0,
    200.0,
    0.0,
    1.0,
    0.0,
    0.5,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Organic Corn');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sea Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Dill Pickles
INSERT IGNORE INTO categories (category) VALUES ('pantry');
SET @category_id = (SELECT id FROM categories WHERE category = 'pantry');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Dill Pickles',
    'H-E-B',
    'public',
    5.0,
    0.0,
    1.0,
    0.0,
    1.0,
    0.0,
    280.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cucumbers');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Vinegar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Garlic');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Dill');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Calcium Chloride');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Organics Diced Tomatoes
INSERT IGNORE INTO categories (category) VALUES ('canned goods');
SET @category_id = (SELECT id FROM categories WHERE category = 'canned goods');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Organics Diced Tomatoes',
    'H-E-B Organics',
    'public',
    25.0,
    1.0,
    3.0,
    1.0,
    5.0,
    0.0,
    240.0,
    0.0,
    0.0,
    0.0,
    0.5,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Organic Tomatoes');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Organic Tomato Juice');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sea Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Calcium Chloride');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Citric Acid');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Orange Juice
INSERT IGNORE INTO categories (category) VALUES ('beverages');
SET @category_id = (SELECT id FROM categories WHERE category = 'beverages');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Orange Juice',
    'H-E-B',
    'public',
    110.0,
    0.0,
    22.0,
    2.0,
    26.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    8.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Orange Juice from Concentrate');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Bakery Scratch Cranberry Pistachio Bread
INSERT IGNORE INTO categories (category) VALUES ('bread');
SET @category_id = (SELECT id FROM categories WHERE category = 'bread');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Bakery Scratch Cranberry Pistachio Bread',
    'H-E-B Bakery',
    'public',
    180.0,
    2.0,
    8.0,
    6.0,
    35.0,
    0.0,
    300.0,
    0.0,
    3.5,
    0.5,
    2.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Enriched Wheat Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Dried Cranberries');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Pistachios');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Yeast');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Soybean Oil');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B That Green Sauce
INSERT IGNORE INTO categories (category) VALUES ('condiments');
SET @category_id = (SELECT id FROM categories WHERE category = 'condiments');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('tex-mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'tex-mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B That Green Sauce',
    'H-E-B',
    'public',
    40.0,
    1.0,
    1.0,
    0.0,
    2.0,
    0.0,
    200.0,
    0.0,
    0.0,
    0.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tomatillos');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Jalapenos');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Onions');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cilantro');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Garlic');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lime Juice');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Frozen Broccoli Florets
INSERT IGNORE INTO categories (category) VALUES ('frozen');
SET @category_id = (SELECT id FROM categories WHERE category = 'frozen');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Frozen Broccoli Florets',
    'H-E-B',
    'public',
    25.0,
    2.0,
    2.0,
    2.0,
    4.0,
    0.0,
    20.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Broccoli');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Canned Tuna in Water
INSERT IGNORE INTO categories (category) VALUES ('canned goods');
SET @category_id = (SELECT id FROM categories WHERE category = 'canned goods');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Canned Tuna in Water',
    'H-E-B',
    'public',
    50.0,
    0.0,
    0.0,
    20.0,
    0.0,
    40.0,
    250.0,
    0.0,
    1.0,
    0.0,
    2.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tuna');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: H-E-B Honey Graham Crackers
INSERT IGNORE INTO categories (category) VALUES ('snacks');
SET @category_id = (SELECT id FROM categories WHERE category = 'snacks');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('american');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'american');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'H-E-B Honey Graham Crackers',
    'H-E-B',
    'public',
    130.0,
    1.0,
    8.0,
    2.0,
    24.0,
    0.0,
    160.0,
    0.0,
    3.0,
    0.0,
    2.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Enriched Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Graham Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Canola Oil');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Honey');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Baking Soda');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Soy Lecithin');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Soy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Soy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: BFree Foods, Gluten Free, Homestyle Sandwich White Sourdough Loaf, 14.1oz, 1 loaf
INSERT IGNORE INTO categories (category) VALUES ('ingredient');
SET @category_id = (SELECT id FROM categories WHERE category = 'ingredient');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'BFree Foods, Gluten Free, Homestyle Sandwich White Sourdough Loaf, 14.1oz, 1 loaf',
    'BFree',
    'public',
    150.0,
    4.0,
    2.0,
    2.0,
    30.0,
    0.0,
    0.22,
    0.0,
    2.5,
    0.5,
    2.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'food');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: fairlife Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz
INSERT IGNORE INTO categories (category) VALUES ('ingredient');
SET @category_id = (SELECT id FROM categories WHERE category = 'ingredient');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'fairlife Lactose Free Fat Free Ultra Filtered Milk, 52 fl oz',
    'fairlife',
    'public',
    80.0,
    0.0,
    6.0,
    13.0,
    6.0,
    0.005,
    0.12,
    0.0,
    0.0,
    0.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'NONFAT ULTRA-FILTERED MILK');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'LACTASE ENZYME');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'VITAMIN A PALMITATE');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'VITAMIN D3.');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Lactose');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Lactose');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Central Market Organics Baby Spinach
INSERT IGNORE INTO categories (category) VALUES ('produce');
SET @category_id = (SELECT id FROM categories WHERE category = 'produce');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Central Market Organics Baby Spinach',
    'Central Market',
    'public',
    35.0,
    2.0,
    1.0,
    3.0,
    4.0,
    0.0,
    65.0,
    0.0,
    0.5,
    0.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Organic Baby Spinach');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Mi Tienda by H-E-B Refried Pinto Beans
INSERT IGNORE INTO categories (category) VALUES ('canned goods');
SET @category_id = (SELECT id FROM categories WHERE category = 'canned goods');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('tex-mex');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'tex-mex');
INSERT INTO foods (
    name, brand, publication_status, cal, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Mi Tienda by H-E-B Refried Pinto Beans',
    'Mi Tienda by H-E-B',
    'public',
    195.0,
    6.0,
    0.0,
    7.0,
    20.0,
    10.0,
    460.0,
    0.0,
    4.5,
    2.0,
    0.5,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Pinto Beans');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lard');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Pork');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Pork');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


UPDATE foods SET publication_status = 'public' WHERE user_id = @system_user_id;
