-- Allergy Snatcher Food Import Script
-- Generated by dataimport.py

-- Create a placeholder 'System' user for data attribution
-- and set a variable for its ID.
INSERT IGNORE INTO users (username, email, role, first_name) VALUES ('System', 'system@local.host', 'admin', 'System');
SET @system_user_id = (SELECT id FROM users WHERE username = 'System');

-- Processing food: MRE - Chili Mac
INSERT IGNORE INTO categories (category) VALUES ('Shelf-Stable Meal');
SET @category_id = (SELECT id FROM categories WHERE category = 'Shelf-Stable Meal');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Military');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Military');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'MRE - Chili Mac',
    'US Gov''t Surplus',
    'public',
    6.0,
    8.0,
    18.0,
    45.0,
    55.0,
    1100.0,
    1.0,
    20.0,
    8.0,
    227.0,
    'g',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cooked Pasta');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Beef Crumbles');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tomato Sauce');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Kidney Beans');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cheese Sauce');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Modified Food Starch');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Shadow-Bean Coffee
INSERT IGNORE INTO categories (category) VALUES ('Beverage (Grounds)');
SET @category_id = (SELECT id FROM categories WHERE category = 'Beverage (Grounds)');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Shadow-Bean Coffee',
    'Umbral Roasters',
    'public',
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    0.0,
    2.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, '100% Void-Roasted Arabica Beans');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Sugar-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Sugar-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Dairy-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Dairy-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Slime-Mold Jelly
INSERT IGNORE INTO categories (category) VALUES ('Condiment');
SET @category_id = (SELECT id FROM categories WHERE category = 'Condiment');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Monster');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Monster');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Slime-Mold Jelly',
    'Ooze Organics',
    'public',
    0.0,
    12.0,
    0.0,
    13.0,
    0.0,
    10.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'tbsp',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cultured Slime Gelatin');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Fruit Pectin');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Citric Acid');


-- Processing food: Steamed Hams
INSERT IGNORE INTO categories (category) VALUES ('Fast Food');
SET @category_id = (SELECT id FROM categories WHERE category = 'Fast Food');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('American');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'American');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Steamed Hams',
    'Krusty Burger',
    'public',
    2.0,
    7.0,
    22.0,
    40.0,
    80.0,
    980.0,
    1.5,
    25.0,
    10.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, '100% Beef Patty');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Bun');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lettuce');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Special Sauce');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Gluten');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Gluten');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Beef');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Beef');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Glimmerwing Nectar
INSERT IGNORE INTO categories (category) VALUES ('Beverage');
SET @category_id = (SELECT id FROM categories WHERE category = 'Beverage');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Elven');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Elven');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Glimmerwing Nectar',
    'Feywild Botanicals',
    'public',
    0.0,
    8.0,
    0.0,
    8.0,
    0.0,
    5.0,
    0.0,
    0.0,
    0.0,
    8.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Dewdrops');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Liquefied Moonlight');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Crushed Pixie Petals');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Ancient Grain Crackers
INSERT IGNORE INTO categories (category) VALUES ('Crackers');
SET @category_id = (SELECT id FROM categories WHERE category = 'Crackers');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Ancient Grain Crackers',
    'Pharaoh''s Fields',
    'public',
    3.0,
    0.0,
    3.0,
    18.0,
    0.0,
    190.0,
    0.0,
    7.0,
    0.5,
    6.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Spelt Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Amaranth');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Quinoa');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sunflower Oil');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sea Salt');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Mecha-Munch Nuts & Bolts Mix
INSERT IGNORE INTO categories (category) VALUES ('Snack Mix');
SET @category_id = (SELECT id FROM categories WHERE category = 'Snack Mix');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Robotic');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Robotic');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Mecha-Munch Nuts & Bolts Mix',
    'Roboto Snacks',
    'public',
    4.0,
    2.0,
    9.0,
    10.0,
    0.0,
    180.0,
    0.0,
    22.0,
    3.5,
    40.0,
    'g',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Titanium-Salted Peanuts');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cashew "Gears"');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Almond "Sprockets"');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lubricant (Oil)');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Nuts');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Nuts');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Cosmic Crunch Cereal
INSERT IGNORE INTO categories (category) VALUES ('Breakfast Cereal');
SET @category_id = (SELECT id FROM categories WHERE category = 'Breakfast Cereal');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Intergalactic');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Intergalactic');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Cosmic Crunch Cereal',
    'Galaxy Foods',
    'public',
    4.0,
    12.0,
    3.0,
    35.0,
    0.0,
    150.0,
    0.0,
    5.0,
    1.0,
    1.5,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Puffed Quasars');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Dried Nebula Berries');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Crystallized Stardust');


-- Processing food: Vampire's Kiss Soda
INSERT IGNORE INTO categories (category) VALUES ('Soda');
SET @category_id = (SELECT id FROM categories WHERE category = 'Soda');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Gothic');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Gothic');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Vampire''s Kiss Soda',
    'Nocturne Beverages',
    'public',
    0.0,
    38.0,
    0.0,
    38.0,
    0.0,
    30.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Carbonated Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cane Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Citric Acid');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Natural Pomegranate Flavor');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Red #40');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Caffeinated');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Caffeinated');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Arctic Ice Cream (Mint Shard)
INSERT IGNORE INTO categories (category) VALUES ('Frozen Dessert');
SET @category_id = (SELECT id FROM categories WHERE category = 'Frozen Dessert');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Arctic Ice Cream (Mint Shard)',
    'Polar Pantry',
    'public',
    1.0,
    18.0,
    3.0,
    20.0,
    45.0,
    50.0,
    0.5,
    14.0,
    9.0,
    0.66,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cream');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Peppermint Extract');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Dark Chocolate Shards');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Cyber-Coated Energy Bar
INSERT IGNORE INTO categories (category) VALUES ('Snack Bar');
SET @category_id = (SELECT id FROM categories WHERE category = 'Snack Bar');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Cyberpunk');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Cyberpunk');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Cyber-Coated Energy Bar',
    'NeoCorp Dynamics',
    'public',
    5.0,
    10.0,
    20.0,
    25.0,
    10.0,
    100.0,
    0.0,
    12.0,
    4.0,
    60.0,
    'g',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Protein Isolate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Nano-Oats');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Synthetic Honey');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Chromium Drizzle');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('High-Protein');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'High-Protein');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Grog (Canned)
INSERT IGNORE INTO categories (category) VALUES ('Beverage');
SET @category_id = (SELECT id FROM categories WHERE category = 'Beverage');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Pirate');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Pirate');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Grog (Canned)',
    'Pirate''s Choice',
    'public',
    0.0,
    39.0,
    0.0,
    40.0,
    0.0,
    15.0,
    0.0,
    0.0,
    0.0,
    12.0,
    'oz',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Grog Base (Water, "Rum" Flavor)');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'High Fructose Corn Syrup');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lime Juice Concentrate');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, '\"Scurvy-Preventing" Vitamin C');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Non-Alcoholic');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Non-Alcoholic');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Magma Crisps
INSERT IGNORE INTO categories (category) VALUES ('Snack');
SET @category_id = (SELECT id FROM categories WHERE category = 'Snack');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Volcanic');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Volcanic');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Magma Crisps',
    'Vulcan Snacks',
    'public',
    1.0,
    0.0,
    2.0,
    25.0,
    0.0,
    450.0,
    0.0,
    15.0,
    2.0,
    28.0,
    'g',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Obsidian Flakes');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sulfur Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lava Essence (Flavoring)');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Spicy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Spicy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Sky-Berry Yogurt
INSERT IGNORE INTO categories (category) VALUES ('Dairy');
SET @category_id = (SELECT id FROM categories WHERE category = 'Dairy');
SET @cuisine_id = NULL;
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Sky-Berry Yogurt',
    'Nimbus Dairy',
    'public',
    1.0,
    18.0,
    6.0,
    22.0,
    25.0,
    80.0,
    0.0,
    8.0,
    5.0,
    150.0,
    'g',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cultured Milk');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cloudberries');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cane Sugar');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Live Cultures');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Contains Dairy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Contains Dairy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Dwarven Rock-Bread
INSERT IGNORE INTO categories (category) VALUES ('Bread');
SET @category_id = (SELECT id FROM categories WHERE category = 'Bread');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Dwarven');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Dwarven');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Dwarven Rock-Bread',
    'Ironforge Bakery',
    'public',
    15.0,
    1.0,
    10.0,
    50.0,
    0.0,
    300.0,
    0.0,
    2.0,
    0.5,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Stoneground Wheat');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Basalt Flour');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Yeast');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('High-Fiber');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'High-Fiber');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Dragon's Breath Chili (Canned)
INSERT IGNORE INTO categories (category) VALUES ('Canned Goods');
SET @category_id = (SELECT id FROM categories WHERE category = 'Canned Goods');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('American');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'American');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Dragon''s Breath Chili (Canned)',
    'Wyvern Kitchen',
    'public',
    8.0,
    6.0,
    20.0,
    25.0,
    50.0,
    950.0,
    1.0,
    18.0,
    7.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Ground Beef');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Kidney Beans');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Tomato Puree');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Ghost Peppers');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Onion');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Spices');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Extremely Spicy');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Extremely Spicy');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Zero-G Gelatin Bites
INSERT IGNORE INTO categories (category) VALUES ('Dessert');
SET @category_id = (SELECT id FROM categories WHERE category = 'Dessert');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Space-faring');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Space-faring');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Zero-G Gelatin Bites',
    'AstroEats',
    'public',
    0.0,
    0.0,
    2.0,
    0.0,
    0.0,
    40.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Gelatin');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Aspartame');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Artificial Flavor');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Potassium Sorbate');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Sugar-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Sugar-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Cryo-Stasis Popsicle
INSERT IGNORE INTO categories (category) VALUES ('Frozen Dessert');
SET @category_id = (SELECT id FROM categories WHERE category = 'Frozen Dessert');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Sci-Fi');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Sci-Fi');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Cryo-Stasis Popsicle',
    'Future Freeze',
    'public',
    0.0,
    0.0,
    0.0,
    3.0,
    0.0,
    5.0,
    0.0,
    0.0,
    0.0,
    1.0,
    'item',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Water');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Blue Raspberry Flavoring');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Citric Acid');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Stabilizers');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sucralose');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Sugar-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Sugar-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Low-Calorie');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Low-Calorie');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Quantum Quinoa Salad
INSERT IGNORE INTO categories (category) VALUES ('Prepared Meal');
SET @category_id = (SELECT id FROM categories WHERE category = 'Prepared Meal');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Fusion');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Fusion');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Quantum Quinoa Salad',
    'Particle Provisions',
    'public',
    5.0,
    3.0,
    7.0,
    30.0,
    0.0,
    250.0,
    0.0,
    10.0,
    1.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Entangled Quinoa');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Diced Bell Peppers');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Cucumber');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Lemon-Vinaigrette');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Vegan');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Vegan');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


-- Processing food: Deep Sea Kelp Noodles
INSERT IGNORE INTO categories (category) VALUES ('Pasta Alternative');
SET @category_id = (SELECT id FROM categories WHERE category = 'Pasta Alternative');
INSERT IGNORE INTO cuisines (cuisine) VALUES ('Atlantean');
SET @cuisine_id = (SELECT id FROM cuisines WHERE cuisine = 'Atlantean');
INSERT INTO foods (
    name, brand, publication_status, dietary_fiber, sugars, protein, carbs,
    cholesterol, sodium, trans_fats, total_fats, sat_fats, serving_amt, serving_unit,
    user_id, category_id, cuisine_id
) VALUES (
    'Deep Sea Kelp Noodles',
    'Atlantean Harvest',
    'public',
    3.0,
    0.0,
    2.0,
    10.0,
    0.0,
    600.0,
    0.0,
    1.0,
    0.0,
    1.0,
    'cup',
    @system_user_id,
    @category_id,
    @cuisine_id
);
SET @food_id = LAST_INSERT_ID();

-- Ingredients
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Bioluminescent Kelp');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Sea Salt');
INSERT INTO ingredients (food_id, ingredient_name) VALUES (@food_id, 'Filtered Trench Water');

-- Dietary Restrictions
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Gluten-Free');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Gluten-Free');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);
INSERT IGNORE INTO dietary_restrictions (restriction) VALUES ('Low-Carb');
SET @restriction_id = (SELECT id FROM dietary_restrictions WHERE restriction = 'Low-Carb');
INSERT IGNORE INTO diet_restrict_assoc (food_id, restriction_id) VALUES (@food_id, @restriction_id);


UPDATE foods SET publication_status = 'public' WHERE user_id = @system_user_id;
